dialogs:
  note:
  - 'TITLE <fadeInTicks> <stayTicks> <fadeOutTicks> <message...>'
  - 'MESSAGE <message...>'
  - 'COMMAND <AS_SERVER/AS_PLAYER> <command {player}...>'
  - 'SOUND <bukkitEnum> <pitch 0.0 to 2.0>'
  - 'WAIT <seconds>'
  test:
  - 'TITLE 20 80 20 &6&lNUEVA CAMPAÑA;El comienzo'
  - 'MESSAGE '
  - 'MESSAGE   &6&lHAZ COMENZADO UNA NUEVA CAMPAÑA'
  - 'MESSAGE   &fEsto es solo el comienzo'
  - 'MESSAGE '
  - 'COMMAND AS_SERVER amusic play {player} 5'
  - 'SOUND ENTITY_VILLAGER_AMBIENT 1.0'
  - 'MESSAGE &6[???] &a¡Hola!'
  - 'WAIT 2'
  - 'SOUND ENTITY_VILLAGER_AMBIENT 1.0'
  - 'MESSAGE &6[Juanito] &a¡Me llamo Juanito!'
  - 'WAIT 2'
  - 'SOUND ENTITY_VILLAGER_AMBIENT 1.0'
  - 'MESSAGE &6[Juanito] &a¡Yo sere tu tutor!'
  - 'WAIT 2'
  - 'SOUND ENTITY_VILLAGER_AMBIENT 1.0'
  - 'MESSAGE &6[Juanito] &aEste lugar esta lleno de aventuras y peligros inimaginables,'
  - 'WAIT 3'
  - 'SOUND ENTITY_VILLAGER_AMBIENT 1.0'
  - 'MESSAGE &6[Juanito] &aen donde podras sobrevivir en compañia o en solitario.'
  - 'WAIT 3'
  - 'SOUND ENTITY_VILLAGER_AMBIENT 1.0'
  - 'MESSAGE &6[Juanito] &a¡Tu decides!'
  - 'WAIT 2'
  - 'SOUND ENTITY_VILLAGER_AMBIENT 1.0'
  - 'MESSAGE &6[Juanito] &aPero primero dime como te llamas ...'