dialogs:
  note:
  - 'TITLE <fadeInTicks> <stayTicks> <fadeOutTicks> <message...>'
  - 'MESSAGE <message...>'
  - 'COMMAND <AS_SERVER/AS_PLAYER> <command {player}...>'
  - 'SOUND <bukkitEnum> <pitch 0.5 to 2.0> <volume 0.0 to 2.0>'
  - 'WAIT <20 ticks = 1 second>'
  test:
  - 'TITLE 20 80 20 &6&lNUEVA CAMPAÑA;El comienzo'
  - 'MESSAGE '
  - 'MESSAGE   &6&lHAZ COMENZADO UNA NUEVA CAMPAÑA'
  - 'MESSAGE   &fEsto es solo el comienzo'
  - 'MESSAGE '
  - 'COMMAND AS_SERVER amusic play {player} 5'
  - 'SOUND VILLAGER_IDLE 1.0 1.0'
  - 'MESSAGE &6[???] &a¡Hola!'
  - 'WAIT 40'
  - 'SOUND VILLAGER_IDLE 1.0 1.0'
  - 'MESSAGE &6[Juanito] &a¡Me llamo Juanito!'
  - 'WAIT 40'
  - 'SOUND VILLAGER_IDLE 1.0 1.0'
  - 'MESSAGE &6[Juanito] &a¡Yo sere tu tutor!'
  - 'WAIT 40'
  - 'SOUND VILLAGER_IDLE 1.0 1.0'
  - 'MESSAGE &6[Juanito] &aEste lugar esta lleno de aventuras y peligros inimaginables,'
  - 'WAIT 60'
  - 'SOUND VILLAGER_IDLE 1.0 1.0'
  - 'MESSAGE &6[Juanito] &aen donde podras sobrevivir en compañia o en solitario.'
  - 'WAIT 60'
  - 'SOUND VILLAGER_IDLE 1.0 1.0'
  - 'MESSAGE &6[Juanito] &a¡Tu decides!'
  - 'WAIT 40'
  - 'SOUND VILLAGER_IDLE 1.0 1.0'
  - 'MESSAGE &6[Juanito] &aPero primero dime como te llamas ...'